# frozen_string_literal: true

source "https://rubygems.org"

gem 'capybara'
gem 'capybara'

gem 'cucumber'
gem 'faker'

gem 'pry'
gem 'pry-byebug'
gem 'rspec'

gem 'selenium-webdriver'

gem 'mime-types'
gem 'webdrivers'

# gem 'guard'
# gem 'guard-rspec

# gem "rails" 
