guard 'rspec' do
    # observe os arquivos da pasta /app/views
    watch(%r{^app/views/(.+).html.rb$}) do |m|
      "spec/features/#{m[1]}_spec.rb"
    end
  
    # observe os arquivos da oasta /spec/features
    watch(%r{^spec/features/(.+).rb$}) do |m|
      "spec/features/#{m[1]}.rb"
    end
  end